<a href="https://colab.research.google.com/github/nandini1119-byte/DEMLAI2026/blob/main/9_NumPy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Retail Analytics Assignment

## Business Scenario

**SmartMart Retail Stores** operates five stores across different cities and sells six
major product categories. Management wants to analyse sales performance, expenses,
profits, targets, discounts, inventory and store-level performance using NumPy.

**Run the cells in order** - later questions use arrays created in earlier ones.

# Part 1: Dataset Creation

### Dataset Setup

Create the `stores`, `categories`, `sales_data` and `cost_data` arrays.
Rows represent stores, columns represent product categories.

In [75]:
import numpy as np

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

Display the number of dimensions, shape, total number of values, data type and memory
occupied by `sales_data`.

`ndim` gives the depth of nesting, `shape` the size along each axis, `size` the total
element count, and `nbytes` the memory in bytes.

## Question 2: Store and Category Count

Calculate the total number of stores, product categories and store-category combinations.

The shape tuple gives both counts directly: `shape[0]` is rows (stores) and `shape[1]`
is columns (categories).

In [ ]:
print("no of dimensions  :", sales_data.ndim)
print("shape             :",sales_data.shape)
print("total no of values:",sales_data.size)
print("data type         :",sales_data.dtype)
print("memory occupied   :",sales_data.nbytes)


no of dimensions  : 2
shape             : (5, 6)
total no of values: 30
data type         : int64
memory occupied   : 240


In [ ]:
stores=sales_data.shape[0]
print("total no of stores:",stores)

categories= sales_data.shape[1]
print("product categories:",categories)

store_category = sales_data.size
print("store category combination:",store_category)

## Question 3: Sales Data Type Conversion

Convert `sales_data` into `float32` and `float64`, then compare the memory used by both.

`float32` uses 4 bytes per value and `float64` uses 8, so the same data occupies twice
the memory in `float64`.

In [ ]:
Flo_32 = sales_data.astype(np.float32)
Flo_64 = sales_data.astype(np.float64)
print("orginal data type:",sales_data.dtype, "/", sales_data.nbytes, "bytes")
print("Flo_32:",Flo_32.dtype, "/", Flo_32.nbytes, "bytes")
print("Flo_64:",Flo_64.dtype, "/", Flo_64.nbytes, "bytes")





orginal data type: int64 / 240 bytes
Flo_32: float32 / 120 bytes
Flo_64: float64 / 240 bytes


# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

Extract and display the complete sales row for Bengaluru.

Bengaluru is the first store, so its row index is 0.

In [ ]:
bengaluru_sales = sales_data[0]
print(bengaluru_sales)



for category, sales in zip(categories, bengaluru_sales):
    print(category, ":", sales)

print("Total Sales:", bengaluru_sales.sum())

[850000 420000 310000 275000 190000 225000]
Electronics : 850000
Groceries : 420000
Clothing : 310000
Furniture : 275000
Beauty : 190000
Sports : 225000
Total Sales: 2270000


## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

Mumbai is the fourth store, so its row index is 3.

In [ ]:
mumbai_cost = cost_data[3]
print(mumbai_cost)

[790000 390000 265000 250000 165000 205000]


## Question 6: Electronics Sales Across Stores

Extract the Electronics sales column from `sales_data`.

`[:, 0]` means every row, column 0 - the colon selects all stores.

In [ ]:
electronics_sales = sales_data[:, 0]
print(electronics_sales)

[ 850000  780000  920000 1050000  690000]


## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

Clothing is the third category, so the column index is 2.

In [ ]:
clothing_cost = sales_data[:, 2]
print(clothing_cost)

[310000 295000 340000 375000 280000]


## Question 8: Hyderabad Furniture Performance

Find the Furniture sales, cost and profit for Hyderabad.

Hyderabad is row 1 and Furniture is column 3, so a single `[1, 3]` index reaches the
exact value.

In [ ]:
furniture_sales = sales_data[1,3]
furniture_costs = cost_data[1,3]
furniture_profit = furniture_sales - furniture_cost
print("Hyd furniture sales:",furniture_sales)
print("Hyd furniture cost:",furniture_costs)
print("Hyd furniture profit:",furniture_profit)



Hyd furniture sales: 310000
Hyd furniture cost: 225000
Hyd furniture profit: 85000


## Question 9: Chennai Category Range

Extract Chennai's sales for Groceries, Clothing and Furniture using array slicing.

Chennai is row 2. Those three categories sit at columns 1, 2 and 3, so the slice
`1:4` covers them - the stop index is excluded.

In [ ]:
chennai_sales = sales_data[2, 1:4]
print("Chennai's sales for Groceries, Clothing and Furniture:",chennai_sales)

for category, sales in zip(categories[1:4], chennai_sales):
    print(category, ":", sales)

Chennai's sales for Groceries, Clothing and Furniture: [390000 340000 260000]
Groceries : 390000
Clothing : 340000
Furniture : 260000


## Question 10: Selected Store Analysis

Extract sales for Bengaluru, Chennai and Pune, including only Electronics, Clothing
and Beauty. Use advanced indexing.

`np.ix_()` builds the row-column grid so the selected rows and columns cross correctly.
Passing two plain lists instead would pair them element by element and return only
three values.

In [ ]:
selected_stores = stores[[0, 2, 4]]
selected_categories = categories[[0, 2, 4]]

selected_sales = sales_data[np.ix_([0, 2, 4], [0, 2, 4])]

for i in range(len(selected_stores)):
    print("\n", selected_stores[i])
    for j in range(len(selected_categories)):
        print(selected_categories[j], ":", selected_sales[i, j])


 Bengaluru
Electronics : 850000
Clothing : 310000
Beauty : 190000

 Chennai
Electronics : 920000
Clothing : 340000
Beauty : 185000

 Pune
Electronics : 690000
Clothing : 280000
Beauty : 175000


# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

Calling `.sum()` with no axis collapses the entire array to a single value.

In [ ]:
Total_sales = sales_data.sum()
print("total sales revenue:",Total_sales)

total sales revenue: 11675000


## Question 12: Store-Wise Sales

Calculate total sales revenue for each store and display the result with store names.

`axis=1` collapses the columns, leaving one total per row (store).

In [ ]:
total_sales = sales_data.sum(axis=1)

for store, total in zip(stores, total_sales):
    print(store, ":", total)

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

`axis=0` collapses the rows, leaving one total per column (category).

In [48]:
total_sales_categories = sales_data.sum(axis=0)
for categories, total in zip (categories, total_sales_categories):
  print(categories, ":" ,total )



Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [53]:
average_sales = sales_data.mean(axis=1)
for store, average in zip (stores, average_sales):
  print(store, ":", average)


Bengaluru : 378333.3333333333
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [78]:
average_sales_category = sales_data.mean(axis=0)

for category, avg in zip(categories, average_sales_category):
    print(category, ":", avg)

Electronics : 858000.0
Groceries : 437000.0
Clothing : 320000.0
Furniture : 283000.0
Beauty : 202000.0
Sports : 235000.0


## Question 16: Highest-Selling Store

Identify the index, name and total sales of the store with the highest total sales
using `np.argmax()`.

`argmax` returns the **position** of the largest value, which is then used to look up
the store name.

In [65]:
store_sales = sales_data.sum(axis=1)
max_index = np.argmax(store_sales)

print("Index      :", max_index)
print("Store Name :", stores[max_index])
print("Total Sales:", store_sales[max_index])

Index      : 3
Store Name : Mumbai
Total Sales: 2820000


## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales using `np.argmin()`.

In [66]:
store_sales = sales_data.sum(axis=1)
min_index = np.argmin(store_sales)

print("Index      :", min_index)
print("Store Name :", stores[min_index])
print("Total Sales:", store_sales[min_index])

Index      : 4
Store Name : Pune
Total Sales: 1980000


## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [77]:
category_sales = sales_data.sum(axis=0)

max_sales = np.argmax(category_sales)

print("Index           :", max_sales)
print("Category Name   :", categories[max_sales])
print("Total Sales     :", category_sales[max_sales])




Index           : 0
Category Name   : Electronics
Total Sales     : 4290000


## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [80]:
category_sales = sales_data.sum(axis=0)

min_sales = np.argmin(category_sales)

print("Index           :", min_sales)
print("Category Name   :", categories[min_sales])
print("Total Sales     :", category_sales[min_sales])




Index           : 4
Category Name   : Beauty
Total Sales     : 1010000


# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [85]:
Total_cost = cost_data.sum()
print("company_total_cost:", Total_cost)

company_total_cost: 8600000


## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [99]:
store_cost = cost_data.sum(axis=1)
for store, total in zip (stores, store_cost):
 print(store, ":", total)

Bengaluru : 1665000
Hyderabad : 1685000
Chennai : 1710000
Mumbai : 2065000
Pune : 1475000


## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [98]:
category_cost = cost_data.sum(axis=0)

for category, total in zip(categories, category_cost):
  print(category, ":", total)

Electronics : 3250000
Groceries : 1660000
Clothing : 1145000
Furniture : 1045000
Beauty : 665000
Sports : 835000


## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [102]:
store_cost = cost_data.sum(axis=1)
max_sales = np.argmax(store_cost)

print("index:", max_sales)
print("store name:", stores[max_sales])
print("total:", store_cost[max_sales])

index: 3
store name: Mumbai
total: 2065000


## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [103]:
store_cost = cost_data.sum(axis=1)
lowest_cost_index = np.argmin(store_cost)

print("Lowest-cost store:", stores[lowest_cost_index])
print("Total cost       :", store_cost[lowest_cost_index])

Lowest-cost store: Pune
Total cost       : 1475000


## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [104]:
ategory_cost = cost_data.sum(axis=0)
highest_category_index = np.argmax(category_cost)

print("Most expensive category:", categories[highest_category_index])
print("Total cost             :", category_cost[highest_category_index])

Most expensive category: Electronics
Total cost             : 3250000


# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit for every store and product category using
`profit_data = sales_data - cost_data`, then display the complete profit matrix.

Both arrays share the same `(5, 6)` shape, so the subtraction happens element by
element without any loop.

In [5]:
profit_data = sales_data - cost_data
print("profit matrix")
print(profit_data)

profit matrix
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [11]:
store_profit = profit_data.sum(axis=1)
for store, total in zip(stores,store_profit):
  print( store, ":", total)

Bengaluru : 605000
Hyderabad : 610000
Chennai : 600000
Mumbai : 755000
Pune : 505000


## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

In [12]:
category_profit = profit_data.sum(axis=0)
for category, total in zip(categories, category_profit):
  print( category, ":", total)

Electronics : 1040000
Groceries : 525000
Clothing : 455000
Furniture : 370000
Beauty : 345000
Sports : 340000


## Question 29: Most Profitable Store

Identify the store with the highest total profit and display its name, total sales,
total cost and total profit.

In [20]:
store_sales = sales_data.sum(axis=1)
store_cost = cost_data.sum(axis=1)
store_profit = store_sales - store_cost

# Index of highest profit store
max_index = np.argmax(store_profit)

print("Store Name  :", stores[max_index])
print("Total Sales :", store_sales[max_index])
print("Total Cost  :", store_cost[max_index])
print("Total Profit:", store_profit[max_index])

Store Name  : Mumbai
Total Sales : 2820000
Total Cost  : 2065000
Total Profit: 755000


## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [21]:
store_sales = sales_data.sum(axis=1)
store_cost = cost_data.sum(axis=1)
store_profit = store_sales - store_cost
min_index = np.argmin(store_profit)

print("Store Name  :", stores[min_index])
print("Total Sales :", store_sales[min_index])
print("Total Cost  :", store_cost[min_index])
print("Total Profit:", store_profit[min_index])


Store Name  : Pune
Total Sales : 1980000
Total Cost  : 1475000
Total Profit: 505000


## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [22]:
category_profit = profit_data.sum(axis=0)
best_category_index = np.argmax(category_profit)

print("Most profitable category:", categories[best_category_index])
print("Total profit            :", category_profit[best_category_index])

Most profitable category: Electronics
Total profit            : 1040000


## Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [23]:
category_profit = profit_data.sum(axis=0)
worst_category_index = np.argmin(category_profit)

print("Least profitable category:", categories[worst_category_index])
print("Total profit             :", category_profit[worst_category_index])

Least profitable category: Sports
Total profit             : 340000


## Question 33: Maximum Individual Profit

Find the highest profit from any single store-category combination and display the
profit amount, store name and category. Use `np.unravel_index()`.

`argmax` returns a position in the **flattened** array. `unravel_index` converts that
flat number back into a row and column pair.

In [24]:
profit_data = sales_data - cost_data

max_index = np.argmax(profit_data)

row, col = np.unravel_index(max_index, profit_data.shape)

print("Highest Profit :", profit_data[row, col])
print("Store          :", stores[row])
print("Category       :", categories[col])

Highest Profit : 260000
Store          : Mumbai
Category       : Electronics


## Question 34: Minimum Individual Profit

Find the smallest profit from a store-category combination and display the
corresponding store and category.

In [25]:
flat_position = np.argmin(profit_data)
row, column = np.unravel_index(flat_position, profit_data.shape)

print("Profit amount   :", profit_data[row, column])
print("Store name      :", stores[row])
print("Product category:", categories[column])

Profit amount   : 55000
Store name      : Pune
Product category: Furniture


# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination using
`(profit_data / sales_data) * 100`, rounded to two decimal places.

In [26]:
profit_data = sales_data - cost_data

profit_margin = np.round((profit_data / sales_data) * 100, 2)

print("Profit Margin (%):")
print(profit_margin)

Profit Margin (%):
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using
`Total Store Profit / Total Store Sales x 100`.

The totals are summed **first**, then divided - averaging the individual margins would
give a different and less accurate figure.

In [27]:
store_sales = sales_data.sum(axis=1)
store_cost = cost_data.sum(axis=1)

store_profit = store_sales - store_cost

overall_profit_margin = np.round((store_profit / store_sales) * 100, 2)

for store, margin in zip(stores, overall_profit_margin):
    print(store, ":", margin, "%")

Bengaluru : 26.65 %
Hyderabad : 26.58 %
Chennai : 25.97 %
Mumbai : 26.77 %
Pune : 25.51 %


## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [28]:
category_sales = sales_data.sum(axis=0)
category_cost = cost_data.sum(axis=0)

category_profit = category_sales - category_cost

category_margin = np.round((category_profit / category_sales) * 100, 2)

for category, margin in zip(categories, category_margin):
    print(category, ":", margin, "%")

Electronics : 24.24 %
Groceries : 24.03 %
Clothing : 28.44 %
Furniture : 26.15 %
Beauty : 34.16 %
Sports : 28.94 %


## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [30]:
store_sales = sales_data.sum(axis=1)
store_cost = cost_data.sum(axis=1)

store_profit = store_sales - store_cost

profit_margin = (store_profit / store_sales) * 100

max_index = np.argmax(profit_margin)

print("Store Name   :", stores[max_index])
print("Profit Margin:", round(profit_margin[max_index], 2), "%")

Store Name   : Mumbai
Profit Margin: 26.77 %


## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [31]:
category_sales = sales_data.sum(axis=0)
category_cost = cost_data.sum(axis=0)

category_profit = category_sales - category_cost

category_margin = (category_profit / category_sales) * 100

max_index = np.argmax(category_margin)

print("Category Name :", categories[max_index])
print("Profit Margin :", round(category_margin[max_index], 2), "%")

Category Name : Beauty
Profit Margin : 34.16 %


## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak. Find all store-category
combinations below that threshold and display the store, category, sales, cost, profit
and profit margin. Use Boolean indexing.

`np.where()` on a Boolean matrix returns two arrays - the row positions and the column
positions of every `True` - which are then paired to read the store and category names.

In [38]:
profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100

weak_margin = profit_margin < 22

rows, cols = np.where(weak_margin)

for r, c in zip(rows, cols):
    print("Store       :", stores[r])
    print("Category    :", categories[c])
    print("Sales       :", sales_data[r, c])
    print("Cost        :", cost_data[r, c])
    print("Profit      :", profit_data[r, c])
    print("Margin (%)  :", round(profit_margin[r, c], 2))
    print("-" * 30)

# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than 5,00,000.

A comparison on an array produces a Boolean mask of the same shape. Using that mask as
an index returns only the values where it is `True`.

In [51]:
high_sales = sales_data > 500000
print("Boolean mask:")
print(high_sales)


rows, cols = np.where(sales_data > 500000)

for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c], ":", sales_data[r, c])

Boolean mask:
[[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True  True False False False False]
 [ True False False False False False]]
Bengaluru - Electronics : 850000
Hyderabad - Electronics : 780000
Chennai - Electronics : 920000
Mumbai - Electronics : 1050000
Mumbai - Groceries : 510000
Pune - Electronics : 690000


## Question 42: Low Sales Values

Find all sales values below 2,00,000.

In [53]:
low_sales_mask = sales_data < 200000
low_sales_values = sales_data[low_sales_mask]

print("Low sales values:", low_sales_values)
print("Count:", low_sales_values.size)

rows, cols = np.where(low_sales_mask)
for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c], ":", sales_data[r, c])

Low sales values: [190000 185000 175000]
Count: 3
Bengaluru - Beauty : 190000
Chennai - Beauty : 185000
Pune - Beauty : 175000


## Question 43: High Profit Values

Find all store-category combinations where profit is greater than 1,50,000.

In [61]:
profit_data = sales_data - cost_data

rows, cols = np.where(profit_data > 150000)

for r, c in zip(rows, cols):
    print("Store    :", stores[r])
    print("Category :", categories[c])
    print("Profit   :", profit_data[r, c])
    print("-" *1)

Store    : Bengaluru
Category : Electronics
Profit   : 210000
-
Store    : Hyderabad
Category : Electronics
Profit   : 190000
-
Store    : Chennai
Category : Electronics
Profit   : 220000
-
Store    : Mumbai
Category : Electronics
Profit   : 260000
-
Store    : Pune
Category : Electronics
Profit   : 160000
-


## Question 44: Moderate Sales Range

Find sales values between 2,50,000 and 5,00,000 using `np.logical_and()`.

Python's `and` keyword cannot combine two arrays, so `np.logical_and()` is used to
apply both conditions element by element.

In [64]:
mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
print(sales_data[mask])


[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


## Question 45: Premium Performance

A combination is premium when sales are above 5,00,000 **and** profit is above
1,50,000. Find all premium-performing combinations.

The `&` operator combines two Boolean arrays element by element. Each condition needs
its own brackets because `&` binds tighter than `>`.

In [69]:
profit_data = sales_data - cost_data

premium = (sales_data > 500000) & (profit_data > 150000)

rows, cols = np.where(premium)

for r, c in zip(rows, cols):
    print("Store    :", stores[r])
    print("Category :", categories[c])
    print("Sales    :", sales_data[r, c])
    print("Profit   :", profit_data[r, c])
    print("-" * 30)

Store    : Bengaluru
Category : Electronics
Sales    : 850000
Profit   : 210000
------------------------------
Store    : Hyderabad
Category : Electronics
Sales    : 780000
Profit   : 190000
------------------------------
Store    : Chennai
Category : Electronics
Sales    : 920000
Profit   : 220000
------------------------------
Store    : Mumbai
Category : Electronics
Sales    : 1050000
Profit   : 260000
------------------------------
Store    : Pune
Category : Electronics
Sales    : 690000
Profit   : 160000
------------------------------


## Question 46: Underperforming Combinations

A combination is underperforming when sales are below 2,50,000 **and** the profit
margin is below 25%.

In [70]:
profit_data = sales_data - cost_data

premium = (sales_data > 500000) & (profit_data > 150000)

rows, cols = np.where(premium)

for r, c in zip(rows, cols):
    print("Store    :", stores[r])
    print("Category :", categories[c])
    print("Sales    :", sales_data[r, c])
    print("Profit   :", profit_data[r, c])
    print("-" * 30)

Store    : Bengaluru
Category : Electronics
Sales    : 850000
Profit   : 210000
------------------------------
Store    : Hyderabad
Category : Electronics
Sales    : 780000
Profit   : 190000
------------------------------
Store    : Chennai
Category : Electronics
Sales    : 920000
Profit   : 220000
------------------------------
Store    : Mumbai
Category : Electronics
Sales    : 1050000
Profit   : 260000
------------------------------
Store    : Pune
Category : Electronics
Sales    : 690000
Profit   : 160000
------------------------------


## Question 47: Category Performance Classification

Classify every sales value as `"High"` (at least 5,00,000), `"Medium"` (2,50,000 to
4,99,999) or `"Low"` (below 2,50,000). Use `np.select()`.

`np.select()` checks the condition list in order and applies the first match, so the
conditions do not need to exclude one another manually.

In [77]:
conditions = [
    sales_data >= 500000,
    (sales_data >= 250000) & (sales_data < 500000),

]

choices = ["High", "Medium"]

sales_level = np.select(conditions, choices, default="Unknown")

print(sales_level)

[['High' 'Medium' 'Medium' 'Medium' 'Unknown' 'Unknown']
 ['High' 'Medium' 'Medium' 'Medium' 'Unknown' 'Unknown']
 ['High' 'Medium' 'Medium' 'Medium' 'Unknown' 'Unknown']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Unknown' 'Unknown' 'Unknown']]


## **Part 9: Target-Based Analysis**


Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

Question 48: Target Comparison Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [81]:
import numpy as np
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
comparison = sales_data >= sales_targets

print(comparison)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 51: Best Target-Performing Store Find the store that achieved the highest number of category targets.

In [82]:
target_achievement = sales_data >= sales_targets

targets_achieved = target_achievement.sum(axis=1)

max_index = np.argmax(targets_achieved)

print("Store Name      :", stores[max_index])
print("Targets Achieved:", targets_achieved[max_index])

Store Name      : Mumbai
Targets Achieved: 6


Question 52: Target Achievement by Category Calculate how many stores achieved the target for each product category.

In [84]:
target_achievement = sales_data >= sales_targets

category_target_count = target_achievement.sum(axis=0)

for category, count in zip(categories, category_target_count):
    print(category, ":", count, "stores")

Electronics : 3 stores
Groceries : 2 stores
Clothing : 2 stores
Furniture : 2 stores
Beauty : 2 stores
Sports : 2 stores


Question 53: Sales Target Variance Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [85]:
sales_variance = sales_data - sales_targets

for i, store in enumerate(stores):
    print("\nStore:", store)
    for j, category in enumerate(categories):
        print(category, ":", sales_variance[i, j])


Store: Bengaluru
Electronics : 50000
Groceries : -30000
Clothing : -10000
Furniture : -25000
Beauty : -10000
Sports : -5000

Store: Hyderabad
Electronics : -20000
Groceries : 10000
Clothing : -25000
Furniture : 10000
Beauty : 10000
Sports : 10000

Store: Chennai
Electronics : 120000
Groceries : -60000
Clothing : 20000
Furniture : -40000
Beauty : -15000
Sports : -15000

Store: Mumbai
Electronics : 250000
Groceries : 60000
Clothing : 55000
Furniture : 45000
Beauty : 50000
Sports : 60000

Store: Pune
Electronics : -110000
Groceries : -45000
Clothing : -40000
Furniture : -75000
Beauty : -25000
Sports : -25000


Question 54: Percentage Above or Below Target Calculate the percentage variance from the target using:

Percentage Variance = (Actual Sales - Target Sales) / Target Sales × 100

In [86]:
percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100
print(np.round(percentage_variance, 2))

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


Question 55: Stores Missing Electronics Target Identify stores that failed to achieve the Electronics sales target.*

In [87]:
failed_stores = stores[sales_data[:, 0] < sales_targets[0]]

print("Stores missing Electronics target:")
for store in failed_stores:
    print(store)

Stores missing Electronics target:
Hyderabad
Pune


Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all()

Question 57: Stores Achieving At Least One Target Identify stores that achieved at least one category target.

Use np.any().

In [88]:
target_achievement = sales_data >= sales_targets

all_targets = np.all(target_achievement, axis=1)

for store, achieved in zip(stores, all_targets):
    print(store, ":", achieved)

Bengaluru : False
Hyderabad : False
Chennai : False
Mumbai : True
Pune : False


# **Part 10: Discount Scenario **


SmartMart plans to offer category-wise discounts:

discount_rates = np.array([ 0.10, # Electronics: 10% 0.05, # Groceries: 5% 0.15, # Clothing: 15% 0.12, # Furniture: 12% 0.08, # Beauty: 8% 0.10 # Sports: 10% ]) Question 58: Discount Amount Matrix Calculate the discount amount for each store-category combination.

Question 59: Sales After Discount Calculate the net sales value after applying the category-wise discounts.

In [89]:
discount_rates = np.array([
    0.10,  # Electronics
    0.05,  # Groceries
    0.15,  # Clothing
    0.12,  # Furniture
    0.08,  # Beauty
    0.10   # Sports
])

discount_amount = sales_data * discount_rates

print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.



In [90]:
discount_amount = sales_data * discount_rates
new_sales = sales_data - discount_amount
new_profit = new_sales - cost_data

print(new_profit)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [91]:
discount_amount = sales_data * discount_rates
new_sales = sales_data - discount_amount
new_profit = new_sales - cost_data

new_profit_margin = (new_profit / new_sales) * 100

for i, store in enumerate(stores):
    print("\nStore:", store)

    for j, category in enumerate(categories):
        print(category, ":", round(new_profit_margin[i, j], 2), "%")


Store: Bengaluru
Electronics : 16.34 %
Groceries : 21.05 %
Clothing : 16.51 %
Furniture : 15.29 %
Beauty : 28.49 %
Sports : 20.99 %

Store: Hyderabad
Electronics : 15.95 %
Groceries : 19.91 %
Clothing : 16.25 %
Furniture : 17.52 %
Beauty : 27.54 %
Sports : 21.3 %

Store: Chennai
Electronics : 15.46 %
Groceries : 20.38 %
Clothing : 15.22 %
Furniture : 14.77 %
Beauty : 29.49 %
Sports : 19.9 %

Store: Mumbai
Electronics : 16.4 %
Groceries : 19.5 %
Clothing : 16.86 %
Furniture : 17.65 %
Beauty : 28.26 %
Sports : 21.46 %

Store: Pune
Electronics : 14.65 %
Groceries : 19.43 %
Clothing : 13.87 %
Furniture : 14.14 %
Beauty : 28.57 %
Sports : 21.41 %


Question 62: Loss-Making Transactions Check whether any store-category combination becomes loss-making after discounts.


Display the affected store and category names.

In [92]:
discount_amount = sales_data * discount_rates
new_sales = sales_data - discount_amount
new_profit = new_sales - cost_data

loss_mask = new_profit < 0

rows, cols = np.where(loss_mask)

if len(rows) == 0:
    print("No loss-making transactions after discounts.")
else:
    print("Loss-making transactions:")

    for r, c in zip(rows, cols):
        print("Store    :", stores[r])
        print("Category :", categories[c])
        print("Profit   :", new_profit[r, c])
        print("-" * 30)

No loss-making transactions after discounts.





Question 63: Discount Impact Calculate how much total revenue the company loses because of the proposed discounts.






In [93]:
discount_amount = sales_data * discount_rates

total_discount_loss = discount_amount.sum()

print("Total Revenue Loss Due to Discounts:", total_discount_loss)

Total Revenue Loss Due to Discounts: 1146350.0


Question 64: Store Most Affected by Discounts Identify the store that loses the highest amount of revenue due to discounts.

In [94]:
discount_amount = sales_data * discount_rates

store_discount_loss = discount_amount.sum(axis=1)

max_index = np.argmax(store_discount_loss)

print("Store Name    :", stores[max_index])
print("Revenue Loss  :", store_discount_loss[max_index])

Store Name    : Mumbai
Revenue Loss  : 277150.0


Part 11: Tax and Price Adjustment The government introduces category-wise tax rates:

tax_rates = np.array([ 0.18, 0.05, 0.12, 0.18, 0.18, 0.12 ])


 Question 65: Tax Collection Matrix Calculate the tax collected on sales for each store and category.

In [95]:
tax_rates = np.array([
    0.18,  # Electronics
    0.05,  # Groceries
    0.12,  # Clothing
    0.18,  # Furniture
    0.18,  # Beauty
    0.12   # Sports
])

tax_collection = sales_data * tax_rates

for i, store in enumerate(stores):
    print("\nStore:", store)

    for j, category in enumerate(categories):
        print(category, ":", round(tax_collection[i, j], 2))


Store: Bengaluru
Electronics : 153000.0
Groceries : 21000.0
Clothing : 37200.0
Furniture : 49500.0
Beauty : 34200.0
Sports : 27000.0

Store: Hyderabad
Electronics : 140400.0
Groceries : 23000.0
Clothing : 35400.0
Furniture : 55800.0
Beauty : 37800.0
Sports : 28800.0

Store: Chennai
Electronics : 165600.0
Groceries : 19500.0
Clothing : 40800.0
Furniture : 46800.0
Beauty : 33300.0
Sports : 25800.0

Store: Mumbai
Electronics : 189000.0
Groceries : 25500.0
Clothing : 45000.0
Furniture : 62100.0
Beauty : 45000.0
Sports : 34800.0

Store: Pune
Electronics : 124200.0
Groceries : 20250.0
Clothing : 33600.0
Furniture : 40500.0
Beauty : 31500.0
Sports : 24600.0




Question 66: Sales Including Tax Calculate the final customer billing value after adding tax.


In [96]:
final_billing = sales_data * (1 + tax_rates)
print(final_billing)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection Calculate the total tax collected by each store.

In [97]:
total_tax = sales_data*tax_rates
store_tax = tax_collection.sum(axis=1)
for store, tax in zip(stores, store_tax):
    print(store, ":", round(tax, 2))

Bengaluru : 321900.0
Hyderabad : 321200.0
Chennai : 331800.0
Mumbai : 401400.0
Pune : 274650.0


Question 68: Category-Wise Tax Collection Calculate total tax collected for each category.

In [98]:
tax_collection = sales_data * tax_rates

category_tax = tax_collection.sum(axis=0)

for category, tax in zip(categories, category_tax):
    print(category, ":", round(tax, 2))

Electronics : 772200.0
Groceries : 109250.0
Clothing : 192000.0
Furniture : 254700.0
Beauty : 181800.0
Sports : 141000.0


Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.


In [99]:
tax_collection = sales_data * tax_rates

store_tax = tax_collection.sum(axis=1)

max_index = np.argmax(store_tax)

print("Store Name :", stores[max_index])
print("Tax Amount :", round(store_tax[max_index], 2))

Store Name : Mumbai
Tax Amount : 401400.0


# **Part 12: Array Modification**

Question 70: Updated Pune Electronics Sales The Pune store reports that its Electronics sales were entered incorrectly.



Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [100]:
updated_sales_data = sales_data.copy()

updated_sales_data[4, 0] = 740000

print("Original Pune Electronics Sales :", sales_data[4, 0])
print("Updated Pune Electronics Sales  :", updated_sales_data[4, 0])

Original Pune Electronics Sales : 690000
Updated Pune Electronics Sales  : 740000


Question 71: Revised Beauty Cost Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [101]:
updated_cost_data = cost_data.copy()

updated_cost_data[:, 4] = updated_cost_data[:, 4] * 0.92

print(updated_cost_data)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


Question 72: Furniture Cost Increase Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [102]:
updated_cost_data = cost_data.copy()

updated_cost_data[:, 3] = updated_cost_data[:, 3] * 1.12

print(updated_cost_data)

[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


Question 73: Store Closure Simulation Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [103]:
updated_sales_data = np.delete(sales_data, 4, axis=0)
updated_cost_data = np.delete(cost_data, 4, axis=0)
updated_stores = np.delete(stores, 4)

print("Stores:")
print(updated_stores)

print("\nSales Data:")
print(updated_sales_data)

print("\nCost Data:")
print(updated_cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store A new Delhi store is opened with the following data:



delhi_sales = np.array([ 880000, 475000, 330000, 290000, 215000, 250000 ])

delhi_cost = np.array([ 665000, 360000, 235000, 215000, 145000, 180000 ]) Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [104]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

sales_data = np.vstack((sales_data, delhi_sales))
cost_data = np.vstack((cost_data, delhi_cost))

stores = np.append(stores, "Delhi")

print("Stores:")
print(stores)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]







Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
Add the new category as a column using np.column_stack() or np.hstack().

In [110]:
home_appliance_sales = np.array([
    360000, 325000, 390000, 420000, 295000, 345600
])

home_appliance_cost = np.array([
    265000, 240000, 285000, 305000, 225000, 435600
])

sales_data = np.column_stack((sales_data, home_appliance_sales))
cost_data = np.column_stack((cost_data, home_appliance_cost))

categories = np.append(categories, "Home Appliances")

print("Categories:")
print(categories)

Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']


# **Part 13: Sorting and Ranking**



Question 76: Sort Stores by Sales Sort stores in ascending order based on total sales.

Display store names and sales totals.


In [106]:
total_sales = sales_data.sum(axis=1)

sorted_index = np.argsort(total_sales)

for i in sorted_index:
    print(stores[i], ":", total_sales[i])

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Delhi : 2440000
Mumbai : 2820000


Question 77: Rank Stores by Profit Rank stores from highest to lowest total profit.

Use np.argsort().

In [107]:
total_profit = profit_data.sum(axis=1)

sorted_index = np.argsort(total_profit)[::-1]

for i in sorted_index:
    print(stores[i], ":", total_profit[i])

Mumbai : 755000
Hyderabad : 610000
Bengaluru : 605000
Chennai : 600000
Pune : 505000


Question 78: Sort Categories by Revenue Sort product categories from highest to lowest total revenue.

In [108]:
category_revenue = sales_data.sum(axis=0)

sorted_index = np.argsort(category_revenue)[::-1]

for i in sorted_index:
    print(categories[i], ":", category_revenue[i])

Electronics : 5170000
Groceries : 2660000
Clothing : 1930000
Furniture : 1705000
Sports : 1425000
Beauty : 1225000


Question 79: Top Three Store-Category Sales Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value Store name Category name

In [109]:
flat_index = np.argsort(sales_data.ravel())[-3:][::-1]

rows, cols = np.unravel_index(flat_index, sales_data.shape)

for r, c in zip(rows, cols):
    print("Sales:", sales_data[r, c])
    print("Store:", stores[r])
    print("Category:", categories[c])
    print()

Sales: 1050000
Store: Mumbai
Category: Electronics

Sales: 920000
Store: Chennai
Category: Electronics

Sales: 880000
Store: Delhi
Category: Electronics





Question 80: Bottom Three Profits Find the three lowest profit values in the profit matrix.

In [111]:
flat_index = np.argsort(profit_data.ravel())[:3]

# Convert flat positions to row and column positions
rows, cols = np.unravel_index(flat_index, profit_data.shape)

for r, c in zip(rows, cols):
    print("Profit:", profit_data[r, c])
    print("Store:", stores[r])
    print("Category:", categories[c])
    print()

Profit: 55000
Store: Pune
Category: Furniture

Profit: 60000
Store: Pune
Category: Sports

Profit: 60000
Store: Chennai
Category: Sports



# **Part 14: Statistical Analysis Question **


81: Sales Statistics Calculate the following for the complete sales array:

Minimum Maximum Mean Median Standard deviation Variance 25th percentile 50th percentile 75th percentile




In [112]:
print("Minimum           :", np.min(sales_data))
print("Maximum           :", np.max(sales_data))
print("Mean              :", np.mean(sales_data))
print("Median            :", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))
print("Variance           :", np.var(sales_data))
print("25th Percentile   :", np.percentile(sales_data, 25))
print("50th Percentile   :", np.percentile(sales_data, 50))
print("75th Percentile   :", np.percentile(sales_data, 75))

Minimum           : 175000
Maximum           : 1050000
Mean              : 386919.04761904763
Median            : 317500.0
Standard Deviation: 213767.10094566006
Variance           : 45696373446.71201
25th Percentile   : 250000.0
50th Percentile   : 317500.0
75th Percentile   : 416250.0


Question 82: Store-Wise Standard Deviation Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [113]:
store_std = sales_data.std(axis=1)

for store, std in zip(stores, store_std):
    print(store, ":", round(std, 2))

max_index = np.argmax(store_std)

print("\nStore with most variation:", stores[max_index])
print("Standard Deviation:", round(store_std[max_index], 2))

Bengaluru : 206612.62
Hyderabad : 181195.01
Chennai : 230781.72
Mumbai : 252301.65
Pune : 164512.27
Delhi : 211349.32

Store with most variation: Mumbai
Standard Deviation: 252301.65


Question 83: Category-Wise Standard Deviation Determine which product category has the highest variation in sales across stores.



In [114]:
category_std = sales_data.std(axis=0)

for category, std in zip(categories, category_std):
    print(category, ":", round(std, 2))

max_index = np.argmax(category_std)

print("\nCategory with highest variation:", categories[max_index])
print("Standard Deviation:", round(category_std[max_index], 2))

Electronics : 112163.08
Groceries : 41998.68
Clothing : 31180.48
Furniture : 37795.13
Beauty : 24734.7
Sports : 27801.38
Home Appliances : 40943.32

Category with highest variation: Electronics
Standard Deviation: 112163.08


Question 84: Sales Above Company Average Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [116]:
company_average = sales_data.mean()

above_average = sales_data > company_average

count = np.sum(above_average)

print("Company-wide Average Sales:", company_average)
print("Number of Sales Above Average:", count)

Company-wide Average Sales: 386919.04761904763
Number of Sales Above Average: 14


Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.

In [117]:
mean_sales = sales_data.mean()
std_sales = sales_data.std()

threshold = mean_sales + (1.5 * std_sales)

outliers = sales_data[sales_data > threshold]

print("Mean Sales:", mean_sales)
print("Standard Deviation:", std_sales)
print("Outlier Threshold:", threshold)
print("High-Value Outliers:", outliers)

Mean Sales: 386919.04761904763
Standard Deviation: 213767.10094566006
Outlier Threshold: 707569.6990375377
High-Value Outliers: [ 850000  780000  920000 1050000  880000]


# **Part 15: Reshaping and Transformation**


Question 86: Flatten Sales Data Convert the two-dimensional sales array into a one-dimensional array using:

flatten() ravel() Explain the difference between the two methods.

In [118]:
sales_flatten = sales_data.flatten()
sales_ravel = sales_data.ravel()

print("Using flatten():")
print(sales_flatten)

print("\nUsing ravel():")
print(sales_ravel)

Using flatten():
[ 850000  420000  310000  275000  190000  225000  360000  780000  460000
  295000  310000  210000  240000  325000  920000  390000  340000  260000
  185000  215000  390000 1050000  510000  375000  345000  250000  290000
  420000  690000  405000  280000  225000  175000  205000  295000  880000
  475000  330000  290000  215000  250000  345600]

Using ravel():
[ 850000  420000  310000  275000  190000  225000  360000  780000  460000
  295000  310000  210000  240000  325000  920000  390000  340000  260000
  185000  215000  390000 1050000  510000  375000  345000  250000  290000
  420000  690000  405000  280000  225000  175000  205000  295000  880000
  475000  330000  290000  215000  250000  345600]


Question 87: Reshape Sales Data Reshape the 5 × 6 sales array into:

3 × 10 10 × 3 2 × 15 15 × 2 Verify that no data is lost.

In [119]:
original_size = sales_data.size

# Reshape into different shapes with total elements = 42
sales_7x6 = sales_data.reshape(7, 6)
sales_6x7 = sales_data.reshape(6, 7)
sales_3x14 = sales_data.reshape(3, 14)
sales_14x3 = sales_data.reshape(14, 3)

print("7 × 6:")
print(sales_7x6)

print("\n6 × 7:")
print(sales_6x7)

print("\n3 × 14:")
print(sales_3x14)

print("\n14 × 3:")
print(sales_14x3)

# Verify no data is lost
print("\nOriginal values:", original_size)
print("7 × 6 values:", sales_7x6.size)
print("6 × 7 values:", sales_6x7.size)
print("3 × 14 values:", sales_3x14.size)
print("14 × 3 values:", sales_14x3.size)

ValueError: cannot reshape array of size 42 into shape (3,10)

Question 88: Transpose Sales Data Transpose the sales array so that:

Rows represent product categories Columns represent stores Display the new shape.

In [120]:
transposed_sales = sales_data.T

print(transposed_sales)
print("New shape:", transposed_sales.shape)

[[ 850000  780000  920000 1050000  690000  880000]
 [ 420000  460000  390000  510000  405000  475000]
 [ 310000  295000  340000  375000  280000  330000]
 [ 275000  310000  260000  345000  225000  290000]
 [ 190000  210000  185000  250000  175000  215000]
 [ 225000  240000  215000  290000  205000  250000]
 [ 360000  325000  390000  420000  295000  345600]]
New shape: (7, 6)


Question 89: Combined Sales and Cost Array Stack sales_data and cost_data vertically.

Display the resulting shape.

In [121]:
combined_data = np.vstack((sales_data, cost_data))

print(combined_data)
print("Shape:", combined_data.shape)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]
 [ 880000  475000  330000  290000  215000  250000  345600]
 [ 640000  315000  220000  205000  125000  160000  265000]
 [ 590000  350000  210000  225000  140000  170000  240000]
 [ 700000  295000  245000  195000  120000  155000  285000]
 [ 790000  390000  265000  250000  165000  205000  305000]
 [ 530000  310000  205000  170000  115000  145000  225000]
 [ 665000  360000  235000  215000  145000  180000  435600]]
Shape: (12, 7)


Question 90: Store-Level Combined Data Create a three-dimensional array where:

First layer contains sales data Second layer contains cost data Use np.stack().

Display the shape of the new array.

In [122]:
combined_data = np.stack((sales_data, cost_data))

print(combined_data)
print("Shape:", combined_data.shape)

[[[ 850000  420000  310000  275000  190000  225000  360000]
  [ 780000  460000  295000  310000  210000  240000  325000]
  [ 920000  390000  340000  260000  185000  215000  390000]
  [1050000  510000  375000  345000  250000  290000  420000]
  [ 690000  405000  280000  225000  175000  205000  295000]
  [ 880000  475000  330000  290000  215000  250000  345600]]

 [[ 640000  315000  220000  205000  125000  160000  265000]
  [ 590000  350000  210000  225000  140000  170000  240000]
  [ 700000  295000  245000  195000  120000  155000  285000]
  [ 790000  390000  265000  250000  165000  205000  305000]
  [ 530000  310000  205000  170000  115000  145000  225000]
  [ 665000  360000  235000  215000  145000  180000  435600]]]
Shape: (2, 6, 7)


Question 91: Missing Value Detection Find:

Total number of missing values Location of missing values Stores and categories containing missing

In [123]:
missing_mask = np.isnan(sales_data)

# 1. Total number of missing values
total_missing = np.sum(missing_mask)

print("Total Missing Values:", total_missing)

# 2. Location of missing values
rows, cols = np.where(missing_mask)

print("\nLocations of Missing Values:")

for r, c in zip(rows, cols):
    print("Store:", stores[r], "| Category:", categories[c])

# 3. Stores containing missing values
store_missing = np.unique(stores[rows])

print("\nStores containing missing values:")
print(store_missing)

# 4. Categories containing missing values
category_missing = np.unique(categories[cols])

print("\nCategories containing missing values:")
print(category_missing)

Total Missing Values: 0

Locations of Missing Values:

Stores containing missing values:
[]

Categories containing missing values:
[]


Question 92: Replace Missing Values with Zero Replace all missing sales values with zero.

In [124]:
sales_cleaned = sales_data.copy()

# Replace missing values with 0
sales_cleaned[np.isnan(sales_cleaned)] = 0

print(sales_cleaned)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]
 [ 880000  475000  330000  290000  215000  250000  345600]]


Question 93: Replace with Company Average Replace missing values with the overall average of available sales values.

In [125]:
sales_cleaned = sales_data.copy()

# Calculate the average of available sales values
company_average = np.nanmean(sales_cleaned)

# Replace missing values with the company average
sales_cleaned[np.isnan(sales_cleaned)] = company_average

print("Company Average:", company_average)
print("\nUpdated Sales Data:")
print(sales_cleaned)

Company Average: 386919.04761904763

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]
 [ 880000  475000  330000  290000  215000  250000  345600]]


Question 94: Replace with Category Average Replace each missing value with the average sales value of its respective product category.

In [127]:
sales_cleaned = sales_data.copy()

# Calculate average for each category
category_average = np.nanmean(sales_cleaned, axis=0)

# Find missing values
rows, cols = np.where(np.isnan(sales_cleaned))

# Replace each missing value with its category average
for r, c in zip(rows, cols):
    sales_cleaned[r, c] = category_average[c]

print("Category Averages:")
for category, avg in zip(categories, category_average):
    print(category, ":", avg)

print("\nUpdated Sales Data:")
print(sales_cleaned)

Category Averages:
Electronics : 861666.6666666666
Groceries : 443333.3333333333
Clothing : 321666.6666666667
Furniture : 284166.6666666667
Beauty : 204166.66666666666
Sports : 237500.0
Home Appliances : 355933.3333333333

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]
 [ 880000  475000  330000  290000  215000  250000  345600]]


Question 95: Missing Value Impact Compare total sales before and after replacing missing values with zero.

In [128]:
total_before = np.nansum(sales_data)

sales_zero = sales_data.copy()

sales_zero[np.isnan(sales_zero)] = 0

total_after = np.sum(sales_zero)

print("Total Sales Before :", total_before)
print("Total Sales After  :", total_after)
print("Difference         :", total_before - total_after)

Total Sales Before : 16250600
Total Sales After  : 16250600
Difference         : 0


# **Part 17: Conditional Business Decisions**

 Question 96: Store Performance Labels Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000 "Good": Total sales between ₹24,00,000 and ₹28,00,000 "Needs Improvement": Total sales below ₹24,00,000 Use np.select().

In [130]:
total_sales = sales_data.sum(axis=1)

conditions = [
    total_sales > 2800000,
    total_sales >= 2400000,
    total_sales < 2400000
]

labels = [
    "Excellent",
    "Good",
    "Needs Improvement"
]

performance_labels = np.select(conditions, labels, default="Unknown")

for store, label in zip(stores, performance_labels):
    print(store, ":", label)

Bengaluru : Good
Hyderabad : Good
Chennai : Good
Mumbai : Excellent
Pune : Needs Improvement
Delhi : Good


Question 97: Profitability Classification Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000 "Profitable": Profit between ₹1,00,000 and ₹2,00,000 "Low Profit": Profit below ₹1,00,000 "Loss": Profit below zero

In [133]:

conditions = [
    profit_data > 200000,
    (profit_data >= 100000) & (profit_data <= 200000),
    (profit_data >= 0) & (profit_data < 100000),
    profit_data < 0
]

labels = [
    "Highly Profitable",
    "Profitable",
    "Low Profit",
    "Loss"
]

profitability_labels = np.select(conditions, labels, default="Unknown")

for store, category, label in zip(stores, categories, profitability_labels):
    print(store, ":", category, ":", label)




Bengaluru : Electronics : ['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']
Hyderabad : Groceries : ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']
Chennai : Clothing : ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']
Mumbai : Furniture : ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
 'Low Profit']
Pune : Beauty : ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']


Question 98: Expansion Recommendation A store is eligible for expansion when:

Total sales are above ₹25,00,000 Total profit is above ₹7,00,000 Overall profit margin is above 25% Identify eligible stores.

In [137]:
profit_data = sales_data - cost_data

total_sales = sales_data.sum(axis=1)
total_profit = profit_data.sum(axis=1)
profit_margin = (total_profit / total_sales) * 100

eligible_stores = np.where((total_sales > 2500000) & (total_profit > 700000) & (profit_margin > 25))[0]

print("Eligible Stores for Expansion:")
for store_index in eligible_stores:
    print(stores[store_index])

Eligible Stores for Expansion:
Chennai
Mumbai


Question 99: Category Promotion Recommendation A product category should receive additional promotion when:

Average sales are below ₹3,00,000 Profit margin is above 25% Identify the categories that satisfy these conditions.

In [138]:
category_avg_sales = sales_data.mean(axis=0)

# Total profit for each category
category_profit = profit_data.sum(axis=0)


category_total_sales = sales_data.sum(axis=0)

category_profit_margin = (category_profit / category_total_sales) * 100

eligible_categories = np.where((category_avg_sales < 300000) & (category_profit_margin > 25))[0]

print("Eligible Categories for Promotion:")
for category_index in eligible_categories:
    print(categories[category_index])



Eligible Categories for Promotion:
Furniture
Beauty
Sports


Question 100: Cost Optimization Recommendation Find store-category combinations where:

Cost is greater than ₹2,50,000 Profit margin is below 25% These combinations should be reviewed for cost optimization.

In [140]:
profit_margin = (profit_data / sales_data) * 100

# Check both conditions
optimization = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

# Find the positions
rows, cols = np.where(optimization)

# Display store and category
for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Cost:", cost_data[r, c])
    print("Profit Margin:", round(profit_margin[r, c], 2))
    print()

Store: Bengaluru
Category: Electronics
Cost: 640000
Profit Margin: 24.71

Store: Hyderabad
Category: Electronics
Cost: 590000
Profit Margin: 24.36

Store: Hyderabad
Category: Groceries
Cost: 350000
Profit Margin: 23.91

Store: Chennai
Category: Electronics
Cost: 700000
Profit Margin: 23.91

Store: Chennai
Category: Groceries
Cost: 295000
Profit Margin: 24.36

Store: Mumbai
Category: Electronics
Cost: 790000
Profit Margin: 24.76

Store: Mumbai
Category: Groceries
Cost: 390000
Profit Margin: 23.53

Store: Pune
Category: Electronics
Cost: 530000
Profit Margin: 23.19

Store: Pune
Category: Groceries
Cost: 310000
Profit Margin: 23.46

Store: Delhi
Category: Electronics
Cost: 665000
Profit Margin: 24.43

Store: Delhi
Category: Groceries
Cost: 360000
Profit Margin: 24.21

Store: Delhi
Category: Home Appliances
Cost: 435600
Profit Margin: -26.04



# **Part 18: Inventory Scenario**


Use the following inventory arrays:

opening_stock = np.array([ [120, 450, 300, 90, 250, 180], [110, 500, 280, 100, 270, 200], [130, 420, 320, 85, 240, 170], [150, 550, 350, 120, 300, 220], [100, 400, 260, 75, 220, 160] ])

units_sold = np.array([ [95, 380, 240, 65, 190, 140], [85, 420, 230, 75, 210, 155], [105, 350, 270, 60, 180, 130], [125, 470, 295, 90, 235, 175], [75, 330, 205, 55, 165, 120] ]) Question 101: Closing Stock Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [142]:
import numpy as np

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

closing_stock = opening_stock - units_sold

print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification Identify store-category combinations where closing stock is below 30 units.

In [143]:
closing_stock = opening_stock - units_sold


rows, cols = np.where(closing_stock < 30)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Closing Stock:", closing_stock[r, c])
    print()

Store: Bengaluru
Category: Electronics
Closing Stock: 25

Store: Bengaluru
Category: Furniture
Closing Stock: 25

Store: Hyderabad
Category: Electronics
Closing Stock: 25

Store: Hyderabad
Category: Furniture
Closing Stock: 25

Store: Chennai
Category: Electronics
Closing Stock: 25

Store: Chennai
Category: Furniture
Closing Stock: 25

Store: Mumbai
Category: Electronics
Closing Stock: 25

Store: Pune
Category: Electronics
Closing Stock: 25

Store: Pune
Category: Furniture
Closing Stock: 20



Question 103: Stock Availability Percentage Calculate the percentage of opening stock that remains unsold.

In [144]:
closing_stock = opening_stock - units_sold

# Calculate stock availability percentage
availability_percentage = (closing_stock / opening_stock) * 100

print("Stock Availability Percentage:")
print(np.round(availability_percentage, 2))

Stock Availability Percentage:
[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


Question 104: Fast-Moving Products A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [145]:
sold_percentage = (units_sold / opening_stock) * 100


fast_moving = sold_percentage > 80


rows, cols = np.where(fast_moving)


for r, c in zip(rows, cols):
    print(
        "Store:", stores[r],
        "| Category:", categories[c],
        "| Sold:", round(sold_percentage[r, c], 2), "%"
    )

Store: Bengaluru | Category: Groceries | Sold: 84.44 %
Store: Hyderabad | Category: Groceries | Sold: 84.0 %
Store: Hyderabad | Category: Clothing | Sold: 82.14 %
Store: Chennai | Category: Electronics | Sold: 80.77 %
Store: Chennai | Category: Groceries | Sold: 83.33 %
Store: Chennai | Category: Clothing | Sold: 84.38 %
Store: Mumbai | Category: Electronics | Sold: 83.33 %
Store: Mumbai | Category: Groceries | Sold: 85.45 %
Store: Mumbai | Category: Clothing | Sold: 84.29 %
Store: Pune | Category: Groceries | Sold: 82.5 %


Question 105: Category-Wise Units Sold Calculate the total units sold for each product category.

In [146]:
category_units_sold = units_sold.sum(axis=0)

for category, total in zip(categories, category_units_sold):
    print(category, ":", total)

Electronics : 485
Groceries : 1950
Clothing : 1240
Furniture : 345
Beauty : 980
Sports : 720


Question 106: Store-Wise Units Sold Calculate total units sold by each store.

Question 107: Best Store by Unit Sales Identify the store that sold the highest total number of units

In [147]:
store_units_sold = units_sold.sum(axis=1)

for store, total in zip(stores, store_units_sold):
    print(store, ":", total)

Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950


Question 108: Reorder Requirement A store should reorder a category when closing stock is below 25 units.

In [149]:
closing_stock = opening_stock - units_sold

# Find store-category combinations that need reordering
rows, cols = np.where(closing_stock < 25)

for r, c in zip(rows, cols):
    print(
        "Store:", stores[r],
        "| Category:", categories[c],
        "| Closing Stock:", closing_stock[r, c],
        "| Reorder Required"
    )

Store: Pune | Category: Furniture | Closing Stock: 20 | Reorder Required


# **Part 16: Missing Data Scenario**


The company discovers that some sales values were not recorded.

sales_with_missing = np.array([ [850000, 420000, np.nan, 275000, 190000, 225000], [780000, 460000, 295000, np.nan, 210000, 240000], [920000, 390000, 340000, 260000, 185000, 215000], [1050000, np.nan, 375000, 345000, 250000, 290000], [690000, 405000, 280000, 225000, np.nan, 205000] ])

Create a Boolean reorder matrix.

In [150]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

reorder_matrix = np.isnan(sales_with_missing)

print(reorder_matrix)

[[False False  True False False False]
 [False False False  True False False]
 [False False False False False False]
 [False  True False False False False]
 [False False False False  True False]]


Question 109: Reorder Quantity Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [152]:
closing_stock = opening_stock - units_sold

reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0
)

print("Reorder Quantity:")
print(reorder_quantity)

Reorder Quantity:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


# ***Part 19: Advanced NumPy Questions ***


Question 110: Cumulative Store Sales Calculate cumulative category sales for each store using np.cumsum().



In [153]:
cumulative_sales = np.cumsum(sales_data, axis=1)

print(cumulative_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000 2630000]
 [ 780000 1240000 1535000 1845000 2055000 2295000 2620000]
 [ 920000 1310000 1650000 1910000 2095000 2310000 2700000]
 [1050000 1560000 1935000 2280000 2530000 2820000 3240000]
 [ 690000 1095000 1375000 1600000 1775000 1980000 2275000]
 [ 880000 1355000 1685000 1975000 2190000 2440000 2785600]]


Question 111: Cumulative Company Sales Flatten the sales array and calculate cumulative company sales.

In [154]:
sales_flat = sales_data.flatten()

# Calculate cumulative company sales
cumulative_sales = np.cumsum(sales_flat)

print(cumulative_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  2630000  3410000
  3870000  4165000  4475000  4685000  4925000  5250000  6170000  6560000
  6900000  7160000  7345000  7560000  7950000  9000000  9510000  9885000
 10230000 10480000 10770000 11190000 11880000 12285000 12565000 12790000
 12965000 13170000 13465000 14345000 14820000 15150000 15440000 15655000
 15905000 16250600]


Question 112: Sales Difference Between Categories Calculate the difference between consecutive category sales for each store using np.diff().

In [156]:
sales_difference = np.diff(sales_data, axis=1)

print("Difference Between Consecutive Categories:")
print(sales_difference)

Difference Between Consecutive Categories:
[[-430000 -110000  -35000  -85000   35000  135000]
 [-320000 -165000   15000 -100000   30000   85000]
 [-530000  -50000  -80000  -75000   30000  175000]
 [-540000 -135000  -30000  -95000   40000  130000]
 [-285000 -125000  -55000  -50000   30000   90000]
 [-405000 -145000  -40000  -75000   35000   95600]]


Question 113: Unique Sales Values Find all unique sales values in sales_data.

Also count the frequency of each value.

Difference Between Consecutive Categories:
[[-430000 -110000  -35000  -85000   35000  135000]
 [-320000 -165000   15000 -100000   30000   85000]
 [-530000  -50000  -80000  -75000   30000  175000]
 [-540000 -135000  -30000  -95000   40000  130000]
 [-285000 -125000  -55000  -50000   30000   90000]
 [-405000 -145000  -40000  -75000   35000   95600]]


Question 114: Search for Specific Sales Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [157]:
unique_sales, frequency = np.unique(sales_data, return_counts=True)

print("Unique Sales Values:")
print(unique_sales)

print("\nFrequency of Each Value:")
for value, count in zip(unique_sales, frequency):
    print(value, ":", count)

Unique Sales Values:
[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  325000  330000  340000
  345000  345600  360000  375000  390000  405000  420000  460000  475000
  510000  690000  780000  850000  880000  920000 1050000]

Frequency of Each Value:
175000 : 1
185000 : 1
190000 : 1
205000 : 1
210000 : 1
215000 : 2
225000 : 2
240000 : 1
250000 : 2
260000 : 1
275000 : 1
280000 : 1
290000 : 2
295000 : 2
310000 : 2
325000 : 1
330000 : 1
340000 : 1
345000 : 1
345600 : 1
360000 : 1
375000 : 1
390000 : 2
405000 : 1
420000 : 2
460000 : 1
475000 : 1
510000 : 1
690000 : 1
780000 : 1
850000 : 1
880000 : 1
920000 : 1
1050000 : 1


Question 115: Compare Sales and Cost Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [158]:
profitable = sales_data > cost_data

print("Sales > Cost:")
print(profitable)

# Check whether ALL combinations are profitable
all_profitable = np.all(profitable)

print("\nAre all combinations profitable?", all_profitable)

Sales > Cost:
[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True False]]

Are all combinations profitable? False


Question 116: Clip Profit Values For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000 Maximum: ₹2,50,000 Use np.clip() to create a reporting profit array.

In [159]:
reporting_profit = np.clip(profit_data, 75000, 250000)

print("Reporting Profit:")
print(reporting_profit)

Reporting Profit:
[[210000 105000  90000  75000  75000  75000  95000]
 [190000 110000  85000  85000  75000  75000  85000]
 [220000  95000  95000  75000  75000  75000 105000]
 [250000 120000 110000  95000  85000  85000 115000]
 [160000  95000  75000  75000  75000  75000  75000]
 [215000 115000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data Normalize all sales values using min-max normalization:

Normalized Sales = (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [160]:
minimum = sales_data.min()
maximum = sales_data.max()

normalized_sales = (sales_data - minimum) / (maximum - minimum)

print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286
  0.21142857]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571
  0.17142857]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429
  0.24571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857
  0.28      ]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571
  0.13714286]
 [0.80571429 0.34285714 0.17714286 0.13142857 0.04571429 0.08571429
  0.19497143]]


Question 118: Standardize Sales Data Standardize sales using:

Standardized Sales = (Sales - Mean Sales) / Standard Deviation

In [161]:
mean_sales = sales_data.mean()
std_sales = sales_data.std()

standardized_sales = (sales_data - mean_sales) / std_sales

print("Standardized Sales:")
print(standardized_sales)

Standardized Sales:
[[ 2.16628728  0.15475231 -0.35982641 -0.523556   -0.921185   -0.75745541
  -0.12592699]
 [ 1.8388281   0.34187184 -0.42999623 -0.35982641 -0.82762524 -0.68728559
  -0.28965658]
 [ 2.49374647  0.01441266 -0.21948676 -0.59372582 -0.94457495 -0.8042353
   0.01441266]
 [ 3.10188495  0.57577126 -0.05575717 -0.19609681 -0.6405057  -0.45338617
   0.15475231]
 [ 1.41780915  0.08458248 -0.50016606 -0.75745541 -0.99135483 -0.85101518
  -0.42999623]
 [ 2.30662693  0.41204167 -0.26626664 -0.45338617 -0.8042353  -0.6405057
  -0.19329002]]


 Question 119: Round Values Convert profit margin values into:

Two decimal places Nearest whole number Floor values Ceiling values

In [162]:
two_decimal = np.round(profit_margin, 2)

# Nearest whole number
whole_number = np.round(profit_margin)

# Floor values
floor_values = np.floor(profit_margin)

# Ceiling values
ceiling_values = np.ceil(profit_margin)

print("Two Decimal Places:")
print(two_decimal)

print("Nearest Whole Number:")
print(whole_number)

print("Floor Values:")
print(floor_values)

print("Ceiling Values:")
print(ceiling_values)

Two Decimal Places:
[[ 24.71  25.    29.03  25.45  34.21  28.89  26.39]
 [ 24.36  23.91  28.81  27.42  33.33  29.17  26.15]
 [ 23.91  24.36  27.94  25.    35.14  27.91  26.92]
 [ 24.76  23.53  29.33  27.54  34.    29.31  27.38]
 [ 23.19  23.46  26.79  24.44  34.29  29.27  23.73]
 [ 24.43  24.21  28.79  25.86  32.56  28.   -26.04]]
Nearest Whole Number:
[[ 25.  25.  29.  25.  34.  29.  26.]
 [ 24.  24.  29.  27.  33.  29.  26.]
 [ 24.  24.  28.  25.  35.  28.  27.]
 [ 25.  24.  29.  28.  34.  29.  27.]
 [ 23.  23.  27.  24.  34.  29.  24.]
 [ 24.  24.  29.  26.  33.  28. -26.]]
Floor Values:
[[ 24.  25.  29.  25.  34.  28.  26.]
 [ 24.  23.  28.  27.  33.  29.  26.]
 [ 23.  24.  27.  25.  35.  27.  26.]
 [ 24.  23.  29.  27.  34.  29.  27.]
 [ 23.  23.  26.  24.  34.  29.  23.]
 [ 24.  24.  28.  25.  32.  28. -27.]]
Ceiling Values:
[[ 25.  25.  30.  26.  35.  29.  27.]
 [ 25.  24.  29.  28.  34.  30.  27.]
 [ 24.  25.  28.  25.  36.  28.  27.]
 [ 25.  24.  30.  28.  34.  30.  28.]
 [ 24

Question 120: Save and Load Data Save the following arrays as NumPy binary files:

sales_data.npy cost_data.npy profit_data.npy Load them back and verify that the loaded arrays are equal to the original arrays.

In [163]:
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

# Load arrays
loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")

# Verify equality
print("Sales Equal :", np.array_equal(sales_data, loaded_sales))
print("Cost Equal  :", np.array_equal(cost_data, loaded_cost))
print("Profit Equal:", np.array_equal(profit_data, loaded_profit))

Sales Equal : True
Cost Equal  : True
Profit Equal: True




Part 20: Final Retail Analytics Project
Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value
Store Summary
For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility
Category Summary
For every category, display:

Total sales
Total cost
Total profit
Profit margin
Average sales
Number of stores achieving the target
Total units sold
Management Recommendations
Based on the analysis, identify:

Best-performing store
Lowest-performing store
Most profitable category
Lowest-profit category
Store recommended for expansion
Category requiring additional marketing
Store-category combinations needing cost optimization
Store-category combinations requiring inventory reorder
Expected Final Output Format
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity:

In [169]:
import numpy as np

# --------------------------------------------------
# SMARTMART RETAIL PERFORMANCE REPORT
# --------------------------------------------------

# Company Summary
total_sales = np.sum(sales_data)
total_cost = np.sum(cost_data)
total_profit = np.sum(profit_data)
overall_profit_margin = (total_profit / total_sales) * 100

average_transaction_value = np.mean(sales_data)
highest_sales = np.max(sales_data)
lowest_sales = np.min(sales_data)

# --------------------------------------------------
# Store Summary
# --------------------------------------------------

store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)
store_profit_margin = (store_profit / store_sales) * 100

# Number of category targets achieved
target_achieved = (sales_data >= 250000) & (cost_data >= 100000)
target_count = np.sum(target_achieved, axis=1)

# Total units sold
store_units_sold = np.sum(units_sold, axis=1)

# Expansion eligibility
expansion = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_profit_margin > 25)
)

# --------------------------------------------------
# Category Summary
# --------------------------------------------------

category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = np.sum(profit_data, axis=0)
category_profit_margin = (category_profit / category_sales) * 100

average_category_sales = np.mean(sales_data, axis=0)

# Stores achieving each category target
category_target_count = np.sum(target_achieved, axis=0)

# Units sold by category
category_units_sold = np.sum(units_sold, axis=0)

# --------------------------------------------------
# MANAGEMENT RECOMMENDATIONS
# --------------------------------------------------

# Best-performing store = highest total profit
best_store_index = np.argmax(store_profit)

# Lowest-performing store = lowest total profit
lowest_store_index = np.argmin(store_profit)

# Most profitable category
best_category_index = np.argmax(category_profit)

# Lowest-profit category
lowest_category_index = np.argmin(category_profit)

# Store recommended for expansion
eligible_stores = stores[expansion]

# Category requiring additional marketing
marketing = (
    (average_category_sales < 300000) &
    (category_profit_margin > 25)
)
marketing_categories = categories[marketing]

# Cost optimization
cost_optimization = (
    (cost_data > 250000) &
    (store_category_profit_margin := (profit_data / sales_data * 100) < 25)
)

cost_rows, cost_cols = np.where(cost_optimization)

# Inventory reorder
closing_stock = opening_stock - units_sold

reorder = closing_stock < 25

reorder_rows, reorder_cols = np.where(reorder)

reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0
)

# --------------------------------------------------
# FINAL REPORT
# --------------------------------------------------

print("=" * 60)
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("=" * 60)

print("\n## COMPANY SUMMARY")
print("Total Sales:", total_sales)
print("Total Cost:", total_cost)
print("Total Profit:", total_profit)
print("Overall Profit Margin:", round(overall_profit_margin, 2), "%")
print("Average Transaction Value:", round(average_transaction_value, 2))
print("Highest Individual Sales Value:", highest_sales)
print("Lowest Individual Sales Value:", lowest_sales)

# --------------------------------------------------
# STORE SUMMARY
# --------------------------------------------------

print("\n## STORE SUMMARY")

for i in range(len(stores)):
    print("\nStore:", stores[i])
    print("Total Sales:", store_sales[i])
    print("Total Cost:", store_cost[i])
    print("Total Profit:", store_profit[i])
    print("Profit Margin:", round(store_profit_margin[i], 2), "%")
    print("Targets Achieved:", target_count[i])

    print("Expansion Eligible:", expansion[i])

# --------------------------------------------------
# CATEGORY SUMMARY
# --------------------------------------------------

print("\n## CATEGORY SUMMARY")

for i in range(len(categories)):
    print("\nCategory:", categories[i])
    print("Total Sales:", category_sales[i])
    print("Total Cost:", category_cost[i])
    print("Total Profit:", category_profit[i])
    print("Profit Margin:", round(category_profit_margin[i], 2), "%")
    print("Average Sales:", round(average_category_sales[i], 2))
    print("Stores Achieving Target:", category_target_count[i])


# --------------------------------------------------
# BEST-PERFORMING STORE
# --------------------------------------------------

print("\n## BEST-PERFORMING STORE")

i = best_store_index

print("Store:", stores[i])
print("Sales:", store_sales[i])
print("Cost:", store_cost[i])
print("Profit:", store_profit[i])
print("Profit Margin:", round(store_profit_margin[i], 2), "%")

# --------------------------------------------------
# LOWEST-PERFORMING STORE
# --------------------------------------------------

print("\n## LOWEST-PERFORMING STORE")

i = lowest_store_index

print("Store:", stores[i])
print("Sales:", store_sales[i])
print("Cost:", store_cost[i])
print("Profit:", store_profit[i])
print("Profit Margin:", round(store_profit_margin[i], 2), "%")

# --------------------------------------------------
# MOST PROFITABLE CATEGORY
# --------------------------------------------------

print("\n## MOST PROFITABLE CATEGORY")

i = best_category_index

print("Category:", categories[i])
print("Sales:", category_sales[i])
print("Cost:", category_cost[i])
print("Profit:", category_profit[i])
print("Profit Margin:", round(category_profit_margin[i], 2), "%")

# --------------------------------------------------
# LOWEST-PROFIT CATEGORY
# --------------------------------------------------

print("\n## LOWEST-PROFIT CATEGORY")

i = lowest_category_index

print("Category:", categories[i])
print("Sales:", category_sales[i])
print("Cost:", category_cost[i])
print("Profit:", category_profit[i])
print("Profit Margin:", round(category_profit_margin[i], 2), "%")

# --------------------------------------------------
# EXPANSION RECOMMENDATIONS
# --------------------------------------------------

print("\n## EXPANSION RECOMMENDATIONS")

if len(eligible_stores) > 0:
    for store in eligible_stores:
        print("Eligible Store:", store)
else:
    print("No store is eligible for expansion.")

# --------------------------------------------------
# CATEGORY MARKETING
# --------------------------------------------------

print("\n## ADDITIONAL MARKETING")

if len(marketing_categories) > 0:
    for category in marketing_categories:
        print("Category:", category)
else:
    print("No category requires additional marketing.")

# --------------------------------------------------
# COST OPTIMIZATION
# --------------------------------------------------

print("\n## COST OPTIMIZATION")

for r, c in zip(cost_rows, cost_cols):
    print(
        "Store:", stores[r],
        "| Category:", categories[c],
        "| Cost:", cost_data[r, c],
        "| Profit Margin:", round(profit_data[r, c] / sales_data[r, c] * 100, 2), "%"
    )

# --------------------------------------------------
# INVENTORY REORDER
# --------------------------------------------------

print("\n## INVENTORY REORDER")

for r, c in zip(reorder_rows, reorder_cols):
    print(
        "Store:", stores[r],
        "| Category:", categories[c],
        "| Closing Stock:", closing_stock[r, c],
        "| Reorder Quantity:", reorder_quantity[r, c]
    )

SMARTMART RETAIL PERFORMANCE REPORT

## COMPANY SUMMARY
Total Sales: 16250600
Total Cost: 12155600
Total Profit: 4095000
Overall Profit Margin: 25.2 %
Average Transaction Value: 386919.05
Highest Individual Sales Value: 1050000
Lowest Individual Sales Value: 175000

## STORE SUMMARY

Store: Bengaluru
Total Sales: 2630000
Total Cost: 1930000
Total Profit: 700000
Profit Margin: 26.62 %
Targets Achieved: 5
Expansion Eligible: False

Store: Hyderabad
Total Sales: 2620000
Total Cost: 1925000
Total Profit: 695000
Profit Margin: 26.53 %
Targets Achieved: 5
Expansion Eligible: False

Store: Chennai
Total Sales: 2700000
Total Cost: 1995000
Total Profit: 705000
Profit Margin: 26.11 %
Targets Achieved: 5
Expansion Eligible: True

Store: Mumbai
Total Sales: 3240000
Total Cost: 2370000
Total Profit: 870000
Profit Margin: 26.85 %
Targets Achieved: 7
Expansion Eligible: True

Store: Pune
Total Sales: 2275000
Total Cost: 1700000
Total Profit: 575000
Profit Margin: 25.27 %
Targets Achieved: 4
Expansion